### ISSUE TITLE
csfair'e kadar

### ISSUE THREAD

**Issue by calkan** [damlaozgen/SUN#13]
RFID ve "oyun" olarak kullanabilme CSFair'e kadar yetisecek mi?

**Comment by aertan** [comment]
Bir aksilik çıkmazsa yetişecek gibi hocam, üzerinde çalışıyoruz.

**Comment by calkan** [comment]
o zaman ACIL olarak:

5 raporu tek bir spiralli dosyada birlestirin, 3 kopya cikarin. bastirma/spiralleme fisini atmayin, geri odeyebilir bolum.  Sekretere teslim edin.  Bugun saat 15:00'e kadar zamanininiz var.

"Projenin Raporları: Bir proje ait 5 raporun tek bir kitapçık şeklinde bir araya getirip bu kitapçığın 3 kopyasının bölüm sekreterliğine teslim edilmesi gerekmektedir."
