### ISSUE TITLE
CSFair Material

### ISSUE THREAD

**Issue by calkan** [damlaozgen/SUN#6]
-- Arrange available times for a photoshoot. Bring a good quality digital camera.

Please send the following information and files to oznur.tastan@cs.bilkent.edu.tr  by latest April 6 5:00 pm:
- Your email should have the following tittle:  “csfair2015 project info” (otherwise it will              not pass the email filter) 
-  A group photo including your advisor (300 dpi, landscape), to be included in the event catalog. Make sure it is high resolution. Attached is an example.
-  A word document or a text file (not a pdf) which includes:
  project name
  names of the group members (in alphabetical order sorted by the last name)
  innovation expert name
  supervisor name
  jury members ((in alphabetical order sorted by the last name 
  an up-to-date abstract checked by your supervisor (minimum 400, maximum 550 characters including spaces).

**Comment by damlaozgen** [comment]
Merhaba Hocam,

Bu elbette bir bahane değil fakat sınav stresi ve yoğun deadline trafiği
yüzünden grupça yaşadığımız panik nedeniyle maili yanlış anladık,
kendimizce poster ve flyer yapmaya çalışıp yetiştiremeyince iyice
endişelendik. Bir önceki mailimizden dolayı çok özür diliyoruz umarım sizi
çok kızdırmamışızdır. Bu saatte mail atmak durumunda kaldığım için de özür
dilerim ama eğer kızdıysanız bir an önce bu durumu düzeltmemiz gerektiğini
düşündüm. Abstract olarak Öznur hocaya bu paragrafı göndermemiz sizce uygun
olur mu:

SUN application, will be an Android mobile application. The purpose of the
project is to encourage university students to be socially active in
college environment by being informed about upcoming class or social
college events, being able to form or join study groups and hobby
activities. SUN will be a check-­in based system that uses NFC technology
included in the Android phones. Users get points and badges after their
participation to the events controlled by the check-­in system.Location
information provided by the GSM base towers will be used to determine the
user’s position in the campus and NFC technology will provide more accurate
knowledge to check the user’s attendance to the event by guiding user to
bump phones or touch the NFC devices with the phone.

**Comment by calkan** [comment]
Bir email okumak bu kadar zor olmamali. Ayrica max 550 karakter olacagi belirtilmis, sizinki 773. Asagidaki sekilde kisalttim:

SUN aims to encourage university students to be socially active, by being informing students of upcoming both social and academic events, and allowing them to form or join study and interest groups. SUN is a check-­in based system that uses the NFC technology to track user's involvement in activities, and then grants points and badges to participants.
SUN is location-aware through information provided by the GSM base stations. The NFC technology provides a finer grain location information and user's attendance to the events.
